[package]
name = "dev"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
colored = "3.0.0"
regex = "1.11.1"
reqwest = "0.12.12"
scraper = "0.23.1"
tokio = "1.43.0"
